### ISSUE TITLE
[Fix] Cart Payload 수정

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#115]
## 📚 To-do

- [x] check 수정
- [x]  count 수정은 DB쪽이랑 연계된 문제 같다

## 🕐 목표 작업 시간

틈틈히 작업한거라 시간 계산 실패..

**Comment by wjchoi96** [comment]
DiffUtil

areItemsTheSame
- 같은 Item인지 비교
- True가 리턴되면 areContentsTheSame 을 호출
- 같은 item이라면, content비교를 통해 업데이트해야할지 추가로 계산한다는 의미
- false가 리턴되면  해당 Position은 변경 대상으로 취급( onBindViewHolder가 호출될것)

areContentsTheSame
- 같은 content를 가졌는지 비교
- False가 리턴되었을때 getChangePayload를 오버라이딩 하였다면 호출
- 아니라면 해당 Position은 변경 대상으로 취급( onBindViewHolder가 호출될것)

getChangePayload
- 세밀하게 변경해야할 값을 비교하여, 해당 변경에 해당되는 payload를 리턴
- 아니라면 super.getChangePayload(oldItemPosition, newItemPosition) 호출


Header를 areItemsTheSame에서 allCheckState를 사용하여 비교를 진행하셨던데, 사실 Header는 언제나 같은 Item입니다. 
Banchan 으로 예를 들면, 언제나 같은 hash를 지녔지만, 내부의 데이터만 변경되는 것이죠.
Footer도 마찬가지입니다

areItemsTheSame 에서 Header, Footer는 항상 true 가 리턴되어야 합니다
그래야 payload까지 흘러갈수가 있어요.

**Comment by YM-Byun** [comment]
요거 Count 수정 안되던게 저도 DB문제인 줄 알았는데 알고보니 데이터 바인딩에서 cartItem을 갱신하지 않아서 예전 값들이 들어가더라구요.. 그래서 바인딩 해줬습니다!
