### ISSUE TITLE
[Feature] Splash 화면 추가

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#140]
## 📚 To-do

- [x] Splash 화면 추가

**Comment by YM-Byun** [comment]
처음에 `Manifest`의 `application theme`를 `Theme.App.Starting`으로 바꿨습니다.
그렇게 되니 첫 화면은 잘 실행되었지만 `CartActivity`나 `OrderListActivity` 등 다른 Activity를 들어갈 때 `Theme.Appcompat`가 필요하다는 에러가 발생했습니다.

그래서 해결한 방법이 `Manifest`에서 `application theme`은 `Theme.Appcompat`을 상속받은 `Theme.Banchan`으로 설정했고, `RootActivity`의 `Theme`을 `Theme.App.Starting`으로 변경했습니다. 그래서 다른 `Activity`에서 터지는 문제를 해결했습니다.

하지만 Android 9버전의 기기에서 화면 회전시에 `Theme.Appcompat`이 필요하다는 에러 발생했습니다.
그래서 결국 `RootActivity`에 `showSplash`라는 변수를 만들고, `true`일 때는 splash 화면을 보여주고 `false`일 때는 `RootActivity theme`를 직접 `Theme.Banchan`으로 바꿔줘서 해결했습니다.
