### ISSUE TITLE
[Bug] 바텀 다이얼로그 보여진채로 회전시 crash

### ISSUE THREAD

**Issue by Haemin-Park** [woowa-techcamp-2022/android-banchan-06#185]
## 📚 To-do

- [x] BottomSheetDialogFragment 의 생성자에서 인자 제거
- [x] BottomSheetDialogFragment VIewModel 생성 후 적용

## 🕐 목표 작업 시간

08.27 19:45 - 20:10
## 📆 실제 작업 시간

08.27 19:45 - 20:10
08.27 20:30 - 21:07

**Comment by wjchoi96** [comment]
`CartItemInsertBottomSheetFragment`가 보여진채로 화면 회전시에 `crash`가 나던것은, `Fragment`의 생성자에 인자를 추가해놓았기 때문

생성자로 전달받던 변수들을 `argument`를 통해 전달받도록 변경하던 와중, 보통 `Fragment`에서라면 안했을 실수를, `BottomSheetFragment`에서 했다는건 내가 `BottomSheetFragment`를 `Dialog`처럼 인식하고, 사용하고 있었구나 라는 생각이 들었다

그리고 `setRetainInstance` 값을 설정하면 `Activity reCreate`때  기존 인스턴스를 그대로 사용하게 되어서 바로 현재 `Issue`가 해결되는데 `deprecated` 되었길래, 검색을 해보다가 `BottomSheetFragment` 에도 `ViewModel`을 두어 사용하는 코드를 많이 보게 되었다.

이렇게 하면 `DataBinding`에 전달할 함수, 변수들을 `viewModel`로 옮기고, 해당 정보들 대신 `viewModel`을 데이터바인딩 해버리면 신경쓰이던 `public` 문제도 해결이 되는것임을 깨닿자 이전에 Ivy님께서 하신 말씀도 떠올랐다

Adpater, ViewHolder 도 원래 다 ViewModel 생성하고 코드 분리해야하는건데, 편의상 여러분들이 안하고 있는거라고 말씀해 주셨는데, 와닿는것 같은 느낌이 들었다
