### ISSUE TITLE
장바구니에 아이템이 있는데 들어가면 보이지 않는 상황

### ISSUE THREAD

**Issue by Haemin-Park** [woowa-techcamp-2022/android-banchan-06#190]
### 
장바구니를 불러오는중에 에러가 발생했는데, 해당 에러가 제대로 전달이 안되었을때의 문제로 보여진다
- #203 
에 포함하여 에러처리 수정
  
https://user-images.githubusercontent.com/54823396/186851163-6f2fabdf-2283-48fd-b77f-bdae56bb18a6.mp4

## 📚 To-do

- [x] 장바구니를 데이터 요청 중 에러처리 수정

**Comment by wjchoi96** [comment]
- #203 
에 포함하여 에러처리 수정
