### ISSUE TITLE
[Bug] 정렬상태 변경 후, 장바구니에 Item을 넣으면 정렬상태가 변경되는 문제

### ISSUE THREAD

**Issue by psw9999** [woowa-techcamp-2022/android-banchan-06#191]
### 정렬상태 변경 후, 장바구니에 Item을 넣으면 정렬상태가 변경되는 문제
- #183 
포함하여 작업

## 📚 To-do

- [x] 메인요리 처리
- [x] 국물요리 처리
- [x] 반찬 처리

## 🕐 목표 작업 시간

08.28 00:15 - 00:35
## 📆 실제 작업 시간

08.28 00:15 - 00:42

**Comment by YM-Byun** [comment]
4개 탭 다 확인 필요!
