### ISSUE TITLE
[Modify] 백그라운드로 돌리고 최근 앱 목록에서 다시 들어가면 네트워크 스낵바 알림이 또 뜨는 문제 수정

### ISSUE THREAD

**Issue by Haemin-Park** [woowa-techcamp-2022/android-banchan-06#197]
### 백그라운드로 돌리고 최근 앱 목록에서 다시 들어가면 네트워크 스낵바 알림이 또 뜨는 문제 수정

잘 연결되었다는 안내인데, 
이미 연결된 상황에서 최근앱으로 다시 들어갔을땐 안내가 없어도 좋을거같습니다!

## 📚 To-do

- [x] 백그라운드로 돌리고 최근 앱 목록에서 다시 들어가면 네트워크 스낵바 알림이 또 뜨는 문제 수정

**Comment by wjchoi96** [comment]
- #203 
에 포함하여 에러처리 수정
