### ISSUE TITLE
[Fix] Grid item 여백 오류

### ISSUE THREAD

**Issue by YM-Byun** [woowa-techcamp-2022/android-banchan-06#44]
## 📪 Issue

종종 GridView에서 여백이 아상하게 나옴...
### 

## 📚 To-do

- [x] Grid 여백 조절
- [x] Linear 여백 추가

## 🕐 목표 작업 시간

08.15 01:40 - 02:00
## 📆 실제 작업 시간

08.15 01:40 - 01:50

**Comment by wjchoi96** [comment]
원인 - `ItemDecorator` 가 2번 적용되는 문제였다
처음에 화면을 구성할때 기본적으로 `ItemDecorator`을 1번 적용을 해주는데, `viewModeToggle Header`에서 기본값으로 적용되는 `GridMode`를 적용해주느라 `event`가 발생하여 한번 더 `ItemDecorator`를 적용해주는듯 싶다

**Comment by wjchoi96** [comment]
로그를 분석해본 결과, `Event`가 처음에 발생하는곳은 `ViewModel`의 `StateFlow`의 기본값이였다
해결을 위해 처음 `setupRecyclderView` 코드를 제거하고, `flow.collec`t를 통해 setupRecyclderView코드가 실행되도록 처리하였다
