### ISSUE TITLE
[Fix] 국물요리, 밑반찬 종종 바로 안 뜨는 오류

### ISSUE THREAD

**Issue by YM-Byun** [woowa-techcamp-2022/android-banchan-06#45]
## 📪 Issue

종종 국물요리, 밑반찬이 바로 뜨지 않고 다른 탭을 갔다와야 표시가 됨
### 

## 📚 To-do

- [x] 원인 파악
- [x] 임시 해결
- [ ] 근본적인 원인 해결

## 🕐 목표 작업 시간

미정
## 📆 실제 작업 시간

미정

**Comment by wjchoi96** [comment]
ViewPager2 문제점 
1. TabLayout을 선택하여 페이지 이동시 viewPager.setCurrentItem(position, smoothScroll=true) 을 호출하여 페이지 이동. 이때 position + 1페이지도 미리 준비하게 된다(onStart까지 호출)
2. 다음 페이지의 onStart()까지 호출되므로, fetchData 메소드를 실행하게 되고, 그에 대한 응답값의 collect, Diffutil.Callback의 계산 처리까지 잘 진행된다. 다만 Adpater의 onCreateViewHolder, onBindViewHolder는 호출되지 않는다.
3. 해당 페이지로 이동하여 onReumse()이 호출되지만, 페이지의 뷰들은 그려지지 않는다. 아주 약간의 이벤트(아무곳이나 터치, 약간의 드래그 등)만 있어도 바로 뷰가 그려진다.
4. RecyclerView 뿐 아니라, TextView도 업데이트되어야 하는 내용이 적용되어 있지않는것을 테스트해봄

원인
1. 아직 찾지 못함. 다만 비슷한 코드의 다른조는 이런 현상이 일어나지 않았다

+ 이상현상
1. Position[1] item tab을 클랙시 onPageSelected가 2번뜬다
    - 모든 페이지의 fetchData()메소드를 비활성화 하니 정상적으로 1번만 뜬다

임시적 해결 조치
- offscreenPageLimit을 1로 설정해주어, 현재 페에지의 +- 1페이지 까지는 그려놓고 있도록 설정

**Comment by wjchoi96** [comment]
시간 관계상 후순위로 밀려서 close 처리
